---

- name: Install fail2ban
  apt: name=fail2ban state=present
  tags: ['fail2ban', 'fail2ban:install']

- name: Copy fail2ban configuration
  template: src={{ fail2ban_jail_local }} dest=/etc/fail2ban/jail.local
  notify: restart fail2ban
  tags: ['fail2ban', 'fail2ban:configuration']
