---

- include: host.yml
  when: tor_daemon_type == "host"

- include: rkt.yml
  when: tor_daemon_type == "rkt"

- name: Create Tor configuration directory
  file: path=/etc/tor state=directory owner=root group=root mode=0755
  tags: ['tor', 'tor:configuration']

- name: Copy Tor configuration file
  template: src={{ tor_torrc }} dest=/etc/tor/torrc
  notify: reload tor
  tags: ['tor', 'tor:configuration']

- name: Enable Tor
  service: name=tor enabled=yes
  tags: ['tor', 'tor:configuration']

- name: Start Tor
  service: name=tor state=started
  tags: ['tor', 'tor:configuration']

- name: Trigger handler to restart Tor
  command: "/bin/true"
  notify: restart tor
  when: tor_restart
  tags: ['tor', 'tor:configuration']
