---

- name: Install UFW
  apt: name=ufw state=present update_cache=yes
  tags: ['ufw', 'ufw:install']

- name: Open ports
  ufw: port={{ item }} rule=allow
  with_items: ufw_open_ports
  tags: ['ufw', 'ufw:configuration']

- name: Open rate limited ports
  ufw: port={{ item }} rule=limit
  with_items: ufw_limited_ports
  tags: ['ufw', 'ufw:configuration']

- name: Close ports
  ufw: port={{ item }} rule=deny
  with_items: ufw_closed_ports
  tags: ['ufw', 'ufw:configuration']

- name: Reject ports
  ufw: port={{ item }} rule=reject
  with_items: ufw_rejected_ports
  tags: ['ufw', 'ufw:configuration']

- name: Set default policy
  ufw: policy={{ ufw_default_policy }}

- name: Trigger handler to set firewall state
  command: "/bin/true"
  notify: set ufw state
  tags: ['ufw', 'ufw:configuration']
